services:
  mongodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234 
      - MONGO_INITDB_DATABASE=mydb

  client:
    tty: true
    stdin_open: true
    depends_on:
      - mongodb
    build: .
    ports: 
      - '3000:3000'
    environment:
      - DATABASE_URL=mongodb://root:1234@mongo:27017/mydb
