version: '3.1'
services:
  mongo:
    build: ./mongodb_replica
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017

  # client:
  #   tty: true
  #   stdin_open: true
  #   depends_on:
  #     - mongo
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     DATABASE_URL: mongodb://admin:password@host.docker.internal:27017/db?authSource=admin
  #   volumes:
  #     - ./src:/app/src
